name: m3

services:
  minio:
    image: minio/minio:latest
    restart: always
    command: server --address ":9000" --console-address ":9001" --certs-dir /certs /data 
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=p@ssw0rd
      - MINIO_REGION=uae
    ports:
      - "9000:9000" # MinIO API Port
      - "9001:9001" # MinIO Console Port
    volumes:
      - ./minio_data:/data
      - ./certs:/certs  # SSL certificates
    

  # nginx:
  #   image: nginx:latest
  #   container_name: nginx
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx config
  #     - ./certs:/etc/nginx/certs  # SSL certificates
  #   ports:
  #     - "443:443"  #External|Internal Expose HTTPS port
  #   depends_on:
  #     - minio
  #   restart: always

volumes:
  minio_data:
    driver: external
